name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Steg 1: Klona repot
      - name: Check out repository
        uses: actions/checkout@v3

      # Steg 2: Installera Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Steg 3: Installera beroenden
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Steg 4: Kör tester
      - name: Run tests in inlupp/exempel
        run: |
          cd inlupp/exempel
          pytest